version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: "agb"
    main: ./cmd/agb
    binary: agb
    flags:
      - -o=./build
    ldflags:
      - -X 'agb/config.appVersion={{ .Env.APP_VERSION }}' -X 'agb/config.goVersion={{ .Env.GO_VERSION }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: "agb"
    format: zip
    builds:
      - "agb"
    name_template: "{{ .ProjectName }}_{{ .Env.APP_VERSION }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: "{{ .ProjectName }}_{{ .Env.APP_VERSION }}_{{ .Os }}_{{ .Arch }}"

release:
  draft: true
