version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

upx:
  - enabled: true
    compress: best
    lzma: true
    # TODO: delete this string when upx fix segfault
    # https://github.com/upx/upx/issues/612
    goos: [linux, windows]

builds:
  - id: "agb"
    main: ./cmd/agb
    binary: agb
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: "agb"
    format: zip
    builds:
      - "agb"
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - docs/
      - scripts/
      - Dockerfile
      - LICENSE.md
      - README.md
