name: Release Candidate

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true

      - name: Export Environment Variables
        run: |
          echo "APP_VERSION=$(bash scripts/get_version.sh)" >> $GITHUB_ENV
          echo "GO_VERSION=$(go version)" >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --snapshot
          workdir: agb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish RC Builds
        uses: ncipollo/release-action@v1
        with:
          draft: true
          skipIfReleaseExists: true
          prerelease: true
          tag: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "dist/*.zip"
